### PR TITLE
support parameters for scripts used with cross-os

### PR DESCRIPTION
**Pull request by Gadatsh**
tests included
note that the tests were tested only on mac-os, wasn't checked on windows and linux (don't have machines running windows or linux). please verify that the tests pass on the other platforms as well

Thanks!

### CODE REVIEW

**Comment by milewski** [comment]
Wow nice job 👍

I just tested it on windows, the tests are failing due to an extra space... im trying to solve it now

```bash
  Loader
    √ should fail if it's invoked with an invalid script (1845ms)
    √ should fail if it's invoked with an invalid script, invoking with parameters (1559ms)
    √ should run the correct script on the right OS (1311ms)
    1) should run the correct script on the right OS and pass the parameters
    √ should fail silently if script for an specific OS is not found (1345ms)
    √ should fail silently if script for an specific OS is not found, invoked with parameters (1430ms)
    √ should work with npm scripts directly (1151ms)
    2) should work with npm scripts directly and pass parameters
    √ should work with npm script + cross-os directly (2520ms)
    3) should work with npm script + cross-os directly and pass parameters
    √ should run scripts defined in cross-os attributes (1354ms)
    4) should run scripts defined in cross-os attributes and pass parameters
    √ should run scripts defined in cross-os attributes (called from npm scripts) (2559ms)
    5) should run scripts defined in cross-os attributes (called from npm scripts) and pass parameters
    √ scripts should have precedence over cross-os attribute (2531ms)
    6) scripts should have precedence over cross-os attribute and pass parameters
    √ should not conflict with script containing the same name as its callee (2550ms)
    √ should not conflict with script containing the same name as its callee and pass parameters (2567ms)
    √ should fail if child fails (1681ms)
    √ should fail if child fails when passing parameters (1936ms)


  14 passing (38s)
  6 failing

  1) Loader
       should run the correct script on the right OS and pass the parameters:
     Error: expected 'hello from win32, I have arguments:  First Second Third\r\n' to match /hello from win32, I have arguments: First Seco
nd Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at Context.<anonymous> (test\test.js:24:38)

  2) Loader
       should work with npm scripts directly and pass parameters:
     Uncaught Error: expected '\'it is working just fine\' with arguments:  "First" "Second" "Third"' to match /it is working just fine wit
h arguments: First Second Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at ChildProcess.<anonymous> (test\test.js:53:38)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

  3) Loader
       should work with npm script + cross-os directly and pass parameters:
     Uncaught Error: expected 'hello from win32, I have arguments:  First Second Third' to match /hello from win32, I have arguments: First
 Second Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at ChildProcess.<anonymous> (test\test.js:77:38)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

  4) Loader
       should run scripts defined in cross-os attributes and pass parameters:
     Error: expected 'hello from cross-os win32, I have arguments:  First Second Third\r\n' to match /hello from cross-os win32, I have arg
uments: First Second Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at Context.<anonymous> (test\test.js:88:38)

  5) Loader
       should run scripts defined in cross-os attributes (called from npm scripts) and pass parameters:
     Uncaught Error: expected 'hello from cross-os win32, I have arguments:  First Second Third' to match /hello from cross-os win32, I hav
e arguments: First Second Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at ChildProcess.<anonymous> (test\test.js:109:38)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

  6) Loader
       scripts should have precedence over cross-os attribute and pass parameters:
     Uncaught Error: expected 'hello from win32, I have arguments:  First Second Third' to match /hello from win32, I have arguments: First
 Second Third/
      at Assertion.assert (node_modules\expect.js\index.js:96:13)
      at Assertion.match (node_modules\expect.js\index.js:328:10)
      at ChildProcess.<anonymous> (test\test.js:133:38)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)



npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! cross-os@1.2.3 tests: `mocha --no-timeouts`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the cross-os@1.2.3 tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rafael\AppData\Roaming\npm-cache\_logs\2018-04-15T13_48_27_694Z-debug.log

```

**Comment by milewski** [comment]
i was thinking that maybe we could set the syntax to be something along these lines:

```json
"scripts": {
  "test": "cross-os foo bar -- arg1",
  "foo": {
    "win32": "echo foo from win32, I have arguments:",
    "linux": "echo foo from linux, I have arguments:",
    "darwin": "echo foo from darwin, I have arguments:"
  },
  "bar": {
    "win32": "echo bar from win32, I have arguments:",
    "linux": "echo bar from linux, I have arguments:",
    "darwin": "echo bar from darwin, I have arguments:"
  }
},
```

Expected output:

```bash
foo from win32, I have arguments: arg1
bar from win32, I have arguments: arg1
```

so we could go even futher `npm run test -- arg2 arg3`

and get 

```
bar from win32, I have arguments: arg1 arg2 arg3
```

i feel that giving the args direcly like this `cross-os bar arg1` is not clearly that the `arg1` will be passed as args to the script, naturally i think the user would assume something like `cross-os bar -- arg1` at the first attempt of passing args unless they dont know what `--` means in bash scripts

im just not sure about `cross-os foo bar` running two scripts... maybe restricting to only one at time is a better way to go? what are your thoughts about this?

**Comment by Gadatsh** [comment]
basically you right, according to https://docs.npmjs.com/cli/run-script, the arguments should be passed to the script using -- with spaces, I actually intended to implement it like that but then I saw it also works without it....

I'm not sure what we're going to get in process.argv when we add '--' for arguments, we need to check if it changes how the arguments are passed to process.argv. 
if it doesn't change anything than we won't have a way to know if the arguments were passed using -- and distinguish between scripts names and arguments in order to add calling more than one script

I think the use case of calling two scripts at once with the same arguments is not that common... do you agree? and in any case you can always use it like that: "cross-os bar -- arg1 && cross-os foo -- arg2"

but does it solve the failed tests in windows?
seems like there are some problems with the spacing of the output...

**Comment by Gadatsh** [comment]
??

**Comment by milewski** [comment]
Ohh sorry i completely missed out the gh notification 😟 

so having this: 

```
"scripts": {
  "test": "cross-os foo -- arg1",
  "foo": {
    "darwin": "echo the arg was: "
  },
},
```

would give to the nodejs an array containing `--` as if it was another param.. so we can find split the args array by `--` if we dont find anything means no args was passed 

if user pass args like this: `cross-os foo arg1` we perhaps can throw an error saying invalid number of args...

**Comment by milewski** [comment]
@Gadatsh can you set `Allow edits from maintainers.` on your pull request? i have made the changes to allow the script to run with -- and fixed the failing tests on windows.

**Comment by milewski** [comment]
actually never mind i have merged it applied my changed and published as `cross-os@1.3.0`  👍

**Comment by Gadatsh** [comment]
I think I did allowed edits from maintainers
anyway that's awesome, thanks a lot for that!
it's been a pleasure using your package 😃

**Pull request merged**
